name: Build and Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Bash on Windows
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: kube-linter --help

  download_test:
    name: Basic download test
    needs: plugin_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run download tests
        run: |
          # Set GITHUB_API_TOKEN for API rate limiting
          export GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
          # Run the download test script for the current architecture
          ./test_download.sh
