name: Build and Test

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 23 * * *"
  pull_request:

jobs:
jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - alpine:latest
          - centos:latest
          - ubuntu:latest

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: asdf-vm/actions/plugin-test@latest
        with:
          command: kube-linter --help

  download_test:
    name: Basic download test
    needs: plugin_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run download tests
        run: |
          # Set GITHUB_API_TOKEN for API rate limiting
          export GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
          # Run the download test script for the current architecture
          ./test_download.sh
