name: Build and Test

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 23 * * *"
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install asdf
        uses: asdf-vm/actions/install@v4

      - name: asdf plugin tests
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: kube-linter --help

  download_test:
    name: Basic download test
    needs: plugin_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run download tests
        run: |
          # Set GITHUB_API_TOKEN for API rate limiting
          export GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
          # Run the download test script for the current architecture
          ./test_download.sh
