name: Test

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 23 * * *"
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        include:
          # Linux amd64
          - os: ubuntu-22.04
            version: "0.5.0"
          - os: ubuntu-22.04
            version: "0.7.2"

          # macOS amd64 (Intel)
          - os: macos-13
            version: "0.5.0"
          - os: macos-13
            version: "0.7.2"

          # Linux arm64
          - os: ubuntu-22.04-arm
            version: "0.7.2"

          # macOS arm64 (Apple Silicon)
          - os: macos-latest
            version: "0.7.2"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run asdf plugin test for version ${{ matrix.version }}
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: kube-linter --help
          version: ${{ matrix.version }}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
