name: Test Downloads

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run weekly to catch any GitHub API or release format changes
    - cron: "0 0 * * 0"

jobs:
  test_linux_x64:
    name: Test Linux x64
    strategy:
      matrix:
        version:
          - "0.7.2" # newer version with 'v' prefix
          - "0.2.0" # older version before 0.5.0 without 'v' prefix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test download for version ${{ matrix.version }}
        shell: bash
        run: |
          # Set GITHUB_API_TOKEN for API rate limiting
          export GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Run the download test script
          ./test_download.sh ${{ matrix.version }}

  test_linux_arm64:
    name: Test Linux ARM64
    strategy:
      matrix:
        version:
          - "0.7.2"
          - "0.2.0"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test download for version ${{ matrix.version }}
        shell: bash
        run: |
          # Set GITHUB_API_TOKEN for API rate limiting
          export GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Run the download test script
          ./test_download.sh ${{ matrix.version }}

  test_macos_intel:
    name: Test macOS Intel
    strategy:
      matrix:
        version:
          - "0.7.2"
          - "0.2.0"
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test download for version ${{ matrix.version }}
        shell: bash
        run: |
          # Set GITHUB_API_TOKEN for API rate limiting
          export GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Run the download test script
          ./test_download.sh ${{ matrix.version }}

  test_macos_arm64:
    name: Test macOS ARM64 (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-14
          - macos-15
        version:
          - "0.7.2"
          - "0.2.0"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test download for version ${{ matrix.version }}
        shell: bash
        run: |
          # Set GITHUB_API_TOKEN for API rate limiting
          export GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Run the download test script
          ./test_download.sh ${{ matrix.version }}
